# Generated by Django 5.1.4 on 2024-12-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_type',
            new_name='usertype',
        ),
    ]
