# Generated by Django 5.1.4 on 2024-12-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctorprofile_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='hospital_name',
        ),
    ]
