# Generated by Django 5.1.4 on 2024-12-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patientprofile_customuser_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
