# Generated by Django 5.1.4 on 2024-12-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uses',
            name='medicines',
            field=models.ManyToManyField(related_name='uses', to='meds.medicine'),
        ),
    ]
