# Generated by Django 5.1.4 on 2025-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_uses_medicines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uses',
            old_name='descritpiton',
            new_name='descripiton',
        ),
        migrations.RemoveField(
            model_name='uses',
            name='medicines',
        ),
        migrations.AddField(
            model_name='medicine',
            name='uses',
            field=models.ManyToManyField(related_name='medicine', to='meds.uses'),
        ),
    ]
