# Generated by Django 5.1.4 on 2025-01-20 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientdata.days')),
            ],
        ),
    ]
