# Generated by Django 5.1.4 on 2025-01-20 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicineschedule',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='patientmedicineschedule',
            name='tags',
            field=models.ManyToManyField(related_name='schedules', to='patientdata.medicinetag'),
        ),
    ]
