# Generated by Django 5.1.4 on 2024-12-25 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinePatientTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name': 'Medicine Patient Tag',
                'verbose_name_plural': 'Medicine Patient Tags',
            },
        ),
        migrations.CreateModel(
            name='MedicineRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100, verbose_name='Medicine Name')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosage')),
                ('time', models.TimeField(verbose_name='Time')),
                ('days_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, verbose_name='Days of the Week')),
                ('dosage_frequency_per_day', models.IntegerField(default=1, verbose_name='Dosage Frequency Per Day')),
                ('dosage_frequency_per_week', models.IntegerField(default=7, verbose_name='Dosage Frequency Per Week')),
                ('is_lifelong', models.BooleanField(default=False, verbose_name='Is Lifelong')),
                ('duration_in_days', models.IntegerField(blank=True, null=True, verbose_name='Duration in Days')),
                ('special_case', models.CharField(blank=True, max_length=255, null=True, verbose_name='Special Case')),
                ('tags', models.ManyToManyField(to='patienthistory.medicinepatienttags', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Medicine Routine',
                'verbose_name_plural': 'Medicine Routines',
                'ordering': ['medicine_name'],
            },
        ),
    ]
