# Generated by Django 5.1.4 on 2024-12-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienthistory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Day of the Week')),
            ],
            options={
                'verbose_name': 'Day of the Week',
                'verbose_name_plural': 'Days of the Week',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='medicineroutine',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='medicineroutine',
            name='days_of_week',
            field=models.ManyToManyField(to='patienthistory.dayofweek', verbose_name='Days of the Week'),
        ),
    ]
