# Generated by Django 5.1.4 on 2024-12-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienthistory', '0002_dayofweek_remove_medicineroutine_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineroutine',
            name='tags',
            field=models.ManyToManyField(blank=True, to='patienthistory.medicinepatienttags', verbose_name='Tags'),
        ),
    ]
