# Generated by Django 5.1.4 on 2024-12-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienthistory', '0004_alter_medicineroutine_user_and_more'),
        ('users', '0005_patientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbloodpressurerecords',
            name='pulse_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pulse Rate'),
        ),
        migrations.AlterField(
            model_name='patientbloodpressurerecords',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patientprofile', verbose_name='User'),
        ),
    ]
